#!/bin/bash


IFS=","

ServerArray=${SERVERS:=$1}


tee /haproxy/haproxy.cfg <<EOF > /dev/null
# this config needs haproxy-1.1.28 or haproxy-1.2.1

global
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  #log loghost  local0 info
  maxconn 500
  #chroot /usr/share/haproxy
  user haproxy
  group haproxy
  daemon
  #debug
  #quiet

listen MySQL 0.0.0.0:3306
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    mode tcp
    option mysql-check user haproxy
EOF

COUNT=1
for i in ${ServerArray[@]}
do
  echo "   " server SERVER_$COUNT $i >> /haproxy/haproxy.cfg
done

cat /haproxy/haproxy.cfg

haproxy -db -f /haproxy/haproxy.cfg
